package com.example.mybolasepak.database.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mybolasepak.database.model.EventDbModel;
import com.example.mybolasepak.database.model.TeamDbModel;

import com.example.mybolasepak.database.model.EventDbModelDao;
import com.example.mybolasepak.database.model.TeamDbModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDbModelDaoConfig;
    private final DaoConfig teamDbModelDaoConfig;

    private final EventDbModelDao eventDbModelDao;
    private final TeamDbModelDao teamDbModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDbModelDaoConfig = daoConfigMap.get(EventDbModelDao.class).clone();
        eventDbModelDaoConfig.initIdentityScope(type);

        teamDbModelDaoConfig = daoConfigMap.get(TeamDbModelDao.class).clone();
        teamDbModelDaoConfig.initIdentityScope(type);

        eventDbModelDao = new EventDbModelDao(eventDbModelDaoConfig, this);
        teamDbModelDao = new TeamDbModelDao(teamDbModelDaoConfig, this);

        registerDao(EventDbModel.class, eventDbModelDao);
        registerDao(TeamDbModel.class, teamDbModelDao);
    }
    
    public void clear() {
        eventDbModelDaoConfig.clearIdentityScope();
        teamDbModelDaoConfig.clearIdentityScope();
    }

    public EventDbModelDao getEventDbModelDao() {
        return eventDbModelDao;
    }

    public TeamDbModelDao getTeamDbModelDao() {
        return teamDbModelDao;
    }

}
